### ISSUE TITLE
SimplePublicObjectWithAssociations properties can be null?

### ISSUE THREAD

**Issue by PanMan** [HubSpot/hubspot-api-nodejs#323] opened 2023-02-08 12:56 UTC
The definition for an API request `hubspotClient.crm.deals.basicApi.getById` states the return type is `SimplePublicObjectWithAssociations` - In the definition it says:
```
export declare class SimplePublicObjectWithAssociations {
    'id': string;
    'properties': {
        [key: string]: string;
    };
.... etc
```
However, we got a crash in our api as one of the `properties` returned was `null`, so not a string.
I'm only just using hubspot, but this seems an error in the types, right?

**Comment by ksvirkou-hubspot** [comment] 2023-02-08 12:59
Hi @PanMan .
I think you can set null string (`let value = ""`).

**Comment by PanMan** [comment] 2023-02-08 13:06
btw, `""` is an empty string (and would be allowed), but we got a `null` value, not empty string

**Comment by ksvirkou-hubspot** [comment] 2023-02-08 13:08
I'll check it as soon as possible.

**Comment by ksvirkou-hubspot** [comment] 2023-02-08 15:11
It is a bug. I'll fix it.

**Comment by ksvirkou-hubspot** [comment] 2023-02-21 08:46
Hey @PanMan .
I can't reproduce it.
Could you provide more details, please? (the peace of code, log of response)

**Comment by ksvirkou-hubspot** [comment] 2023-03-01 08:10
Closing this for now because I can't reproduce it.

**Comment by PanMan** [comment] 2023-03-02 08:25
I don't think this should be closed, and wrote sample code, see below. 
If the type was correct, the deal.properties would always be string, so never `null` but when I run the code below, it does return several deals/properties where they are `null`. Thus the type is not correct
```
import "dotenv/config";
import "../moduleAlias";
import { Client } from "@hubspot/api-client";
import { PublicObjectSearchRequest } from "@hubspot/api-client/lib/codegen/crm/deals";

const hubspotClient = new Client({
  accessToken: process.env.HUBSPOT_API_TOKEN,
});

if (!process.env.HUBSPOT_API_TOKEN) {
  throw new Error("No HUBSPOT_API_TOKEN found");
}

const findDeals = async () => {
  // Find some deals
  const objectSearchRequest: PublicObjectSearchRequest = {
    filterGroups: [
      {
        filters: [
          {
            propertyName: "pipeline",
            operator: "EQ",
            value: "default",
          },
        ],
      },
    ],
    sorts: ["string"],
    properties: ["order_number", "postal_code", "contact", "dealstage"],
    limit: 100,
    after: 0,
  };

  try {
    const apiResponse = await hubspotClient.crm.deals.searchApi.doSearch(
      objectSearchRequest
    );
    console.log("Total results found:", apiResponse.total);
    return apiResponse;
  } catch (e) {
    console.error(e);
    return null;
  }
};

const go = async () => {
  const deals = [];

  const res = await findDeals();
  const moreDeals = res?.results;
  if (moreDeals) {
    deals.push(...moreDeals);
  }

  if (!deals) {
    console.log("No deals found");
    return;
  }

  console.log(
    "status",
    "\t",
    "dealId",
    "\t",
    "order_number",
    "\t",
    "postal_code"
  );

  for (const deal of deals) {
    const dealId = deal.id;
    const dealProperties = deal.properties;
    // Type of dealProperties is:
    // {
    //   [key: string]: string;
    // }

    const status =
      // with type string, this should always be false
      dealProperties.order_number === null ||
      dealProperties.postal_code === null;

    const statusEmoji = status ? "❌" : "✅";
    // However, we do get deals where the order_number or postal_code are null (which can't be according to the type)!!
    // This is a bug in the Hubspot API client library types

    console.log(
      statusEmoji,
      "\t",
      dealId,
      "\t",
      dealProperties.order_number,
      "\t",
      dealProperties.postal_code
    );
  }
};

go();
```

**Comment by ksvirkou-hubspot** [comment] 2023-03-22 14:59
https://github.com/OpenAPITools/openapi-generator/pull/15026

**Comment by ksvirkou-hubspot** [comment] 2023-04-18 14:20
I've already added support of `nullable` to the generator and I asked Hubspot to change appropriate swagger file.
As soon as they do it and I have possibility to regenerate the SDK, I'll do it.

**Comment by ksvirkou-hubspot** [comment] 2023-08-16 11:59
Hey @PanMan .
I've just fixed it in [version 9.1.1](https://www.npmjs.com/package/@hubspot/api-client/v/9.1.1) .

**Closed** 2023-08-21 13:23 UTC
Labels: bug

**Comment by ksvirkou-hubspot** [comment] 2023-08-21 13:25
Feel free to reopen it if you get other errors/questions related with this issue.

**Comment by jamesallchin-rb** [comment] 2023-09-01 08:21
This is really quite a significant and far reaching change between 9.1.0 and 9.1.1.

Essentially `properties` field of  `SimplePublicObject` and `SimplePublicObjectWithAssociations` is not really strongly typed. It essentially can be any property - internal to hubspot (`hs_xxxxx`), or a custom field that was added by the customer. It's not ideal in the first place as it would be nice to know that certain fields internally are not nullable. However, this change is now pretty significant - in typescript we now need to code against the possibility that internal fields (that in the hubspot data model are guaranteed to be there) can be nullable. It's a real pain.

Longer term it would be nicer to get better typing against internal properties (being clear when they are not nullable). 

However, in the interim I'm not really in favour of this change that's gone in. It's a pretty significant breaking change for a minor release.
