### ISSUE TITLE
3.1.0 breaks 3.0.1 contacts import

### ISSUE THREAD

**Issue by Tudes** [HubSpot/hubspot-api-nodejs#27] opened 2021-01-03 12:24 UTC
In case anyone has a similar issue, it doesn't look like the README has been updated for importing contacts using streams.

[first option with fs.ReadStream](https://github.com/HubSpot/hubspot-api-nodejs#first-option-with-fsreadstream).

This will result in an HttpError with the response body

```
{
  "status": "error",
  "message": "Unable to process JSON",
  "correlationId": "****"
}
```

I will test further when I get the chance and will add more info in here, but if you need a quick fix just revert back to 3.0.1

**Comment by Tudes** [comment] 2021-01-03 12:44
It looks like the parameters order has been switched https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/imports/api/coreApi.ts#L179 , not sure if it was intended but having the file first and the import spec second does the job

**Comment by jyotman** [comment] 2021-01-07 03:12
Similar issue -
Parameter order for `hubspotClient.crm.contacts.basicApi.getById` has been changed. Why do we have breaking changes with a minor version upgrade :/

**Comment by mfrye** [comment] 2021-11-05 21:58
I'm on 5.0.0 and the bulk import stream doesn't work for me either. Just returns the same generic message that it's unable to parse json.

Separate from this, what's the status of this lib? The examples are out of date / don't work, it seems that methods have changed, and we're having to go through the code to figure out how to actually do stuff. Is this project dead?

**Comment by ksvirkou-hubspot** [comment] 2023-03-16 13:36
Hi everyone.
I can confirm this issue in these versions.It has been done unintended.
I am sorry for that.
Now I am maintain the SDK and check breaking changes before releases. 
I am closing this issue because these versions is unsupported now.

**Comment by ksvirkou-hubspot** [comment] 2023-03-16 15:41
> I'm on 5.0.0 and the bulk import stream doesn't work for me either. Just returns the same generic message that it's unable to parse json.
> 
> Separate from this, what's the status of this lib? The examples are out of date / don't work, it seems that methods have changed, and we're having to go through the code to figure out how to actually do stuff. Is this project dead?

I maintain this lib now.
If you need help , please create an issue with code example.

**Closed by ksvirkou-hubspot** 2023-03-16 15:41 UTC
